version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean prepare-package war:explode
  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/deploy ./
artifacts:
  files:
    - deploy/**/*
